github_user = ""
github_pwd = ""
github_note = "gthbmining"
github_note_url = "https://github.com/ddangelorb/gthbmining"
github_scopes = ['user', 'repo']
github_token = ""
repo_user = ""
repo_name = ""
params_update = 0